from enum import StrEnum


class EvidenceStatus(StrEnum):
    VERIFIED = "VERIFIED"
    PARTIAL = "PARTIAL"
    IMPLEMENTED_NOT_RUNTIME_VERIFIED = "IMPLEMENTED BUT NOT RUNTIME VERIFIED"
    UNVERIFIED = "UNVERIFIED"
    UNSUPPORTED = "UNSUPPORTED"
    FAILED = "FAILED"
